### ISSUE TITLE
Android App: "Health" Page stays empty

### ISSUE THREAD

**Issue by DerDanilo** [librenms/myLibreNMS#11]
This happens to several different servers including the test server.

Any idea?

**Comment by pheinrichs** [comment]
I'll look into this next week more in depth and see what's up.

**Comment by pheinrichs** [comment]
Alright, so after some testing i was able to get some graphs to display on the health tab on both ios and android, anything that's in the `sensors` table in the db would display just fine. IIRC  the processor, memory and disk usage and a few others are in a different table in the db and not being published by the /health endpoint. 
I'll talk around in the irc and see if it's possible to expose more of the graphs from that endpoint, or what a good solution to this would be.

**Comment by pheinrichs** [comment]
This should be fixed in this PR: https://github.com/librenms/librenms/pull/8728

**Comment by laf** [comment]
Works for me. Thanks @pheinrichs :)
