### ISSUE TITLE
IOS Auth/Issue

### ISSUE THREAD

**Issue by jsdurling** [librenms/myLibreNMS#15]
When adding my Librenms server to the app on IOS, to use the API key, I still have to authenticate with http against the server, for the API key to work.  

Is there a way to provide a username/password within the APP to perform the authentication, and then apply the API key?

Thanks!

**Comment by pheinrichs** [comment]
Is this for basic auth?
I believe you should be able to add the credentials in the URL 
Ex: https://user:pass@librenms.example.com

I tested this out on my dev server and seems to work ok? Or is this something different.

**Comment by jsdurling** [comment]
Yes, adding my username/password into the url worked.  Thank you for confirming.  I didn't try that.

**Comment by laf** [comment]
Imho it would be good to allow people to configure a username/password.

**Comment by pheinrichs** [comment]
I definitely agree, I'm in the process of refactoring a lot of the code so i'll do this after i've finished.
