### ISSUE TITLE
Only 24-hr graphs show

### ISSUE THREAD

**Issue by paraviz02** [librenms/myLibreNMS#19]
For all periods of time (week, year, 24 hour, etc) the 24 hour graph shows.

This is on the new iOS version with the CORS fix on the server.

**Comment by pheinrichs** [comment]
Hmm, I'm unable to replicate this. The graphs are loading fine on my dev and prod servers.

I'm pushing the cors update to apple today so once this is through I'll troubleshoot this some more.

**Comment by paraviz02** [comment]
Very interesting.

One other thing - we are using iPhone X and noticed that we now have full screen (yay!) but there are some interesting layout/format issues.

This may be related.

Will look forward to the new update. Thanks for your efforts!

**Comment by paraviz02** [comment]
Here’s a couple screenshots for you:

Funny layout on iPhone X:
![df7d8b1a-e3cb-420d-9cdd-6d459bf26d4b](https://user-images.githubusercontent.com/6978717/34920010-ac59590c-f920-11e7-8109-72e3ea6bbe05.png)

All 24-hr graphs:
![1b8aa5ee-5d38-449b-b1ad-38a17a99725a](https://user-images.githubusercontent.com/6978717/34920012-bd47c6cc-f920-11e7-9458-3ee8cddae620.png)

**Comment by laf** [comment]
Can confirm it's showing the same graphs. From the logs:

```
1.1.1.1 - - [14/Jan/2018:20:11:52 +0000] "GET /api/v0/devices/398/device_hr_processes?from=end-24h&to=now&width=667&height=200 HTTP/2.0" 200 19967 "http://localhost:8080/var/containers/Bundle/Application/AEEC6533-050E-431C-8FA7-A01DD3509A93/myLibreNMS.app/www/index.html" "Mozilla/5.0 (iPhone; CPU iPhone OS 11_2_2 like Mac OS X) AppleWebKit/604.4.7 (KHTML, like Gecko) Mobile/15C202"
1.1.1.1 - - [14/Jan/2018:20:11:53 +0000] "GET /api/v0/devices/398/device_hr_processes?from=end-1m&to=now&width=667&height=200 HTTP/2.0" 200 14757 "http://localhost:8080/var/containers/Bundle/Application/AEEC6533-050E-431C-8FA7-A01DD3509A93/myLibreNMS.app/www/index.html" "Mozilla/5.0 (iPhone; CPU iPhone OS 11_2_2 like Mac OS X) AppleWebKit/604.4.7 (KHTML, like Gecko) Mobile/15C202"
1.1.1.1 - - [14/Jan/2018:20:11:53 +0000] "GET /api/v0/devices/398/device_hr_processes?from=end-1y&to=now&width=667&height=200 HTTP/2.0" 200 15792 "http://localhost:8080/var/containers/Bundle/Application/AEEC6533-050E-431C-8FA7-A01DD3509A93/myLibreNMS.app/www/index.html" "Mozilla/5.0 (iPhone; CPU iPhone OS 11_2_2 like Mac OS X) AppleWebKit/604.4.7 (KHTML, like Gecko) Mobile/15C202"
1.1.1.1 - - [14/Jan/2018:20:11:53 +0000] "GET /api/v0/devices/398/device_hr_processes?from=end-1w&to=now&width=667&height=200 HTTP/2.0" 200 20520 "http://localhost:8080/var/containers/Bundle/Application/AEEC6533-050E-431C-8FA7-A01DD3509A93/myLibreNMS.app/www/index.html" "Mozilla/5.0 (iPhone; CPU iPhone OS 11_2_2 like Mac OS X) AppleWebKit/604.4.7 (KHTML, like Gecko) Mobile/15C202"
```

It looks like the from= parts. These should just be `-1w`, `-1y`, etc.

I'm trying to get a dev env setup to take a look.

**Comment by pheinrichs** [comment]
I see what you're saying. I think i found this now. Will fix in same patch. Thanks for the help @laf

**Comment by paraviz02** [comment]
Rock on, @pheinrichs ... And thanks @laf for the info!

Y'all are awesome. Thanks again for the beautiful work.

**Comment by laf** [comment]
I’ll submit a pr if you like. Got the fix done.

**Comment by laf** [comment]
Submitted my fix. Works using `ionic serve`

**Comment by pheinrichs** [comment]
1.2.1 push to apple store. Pending approval.

**Comment by pheinrichs** [comment]
New update is in stores now. Let me know if this resolved your issue @paraviz02 and we can close this.

**Comment by paraviz02** [comment]
Thanks so much! Just checked my App Store, still waiting on it to get out my way. Looking forward to it!

I will let you know as soon as I check it out. Thanks again @pheinrichs.

**Comment by paraviz02** [comment]
Yep! All fixed for the graphs.

However, the new version reverted to pre-iPhone X view size on iPhone X. :-)

You may close the issue, as reported, all fixed!

**Comment by pheinrichs** [comment]
Great to hear. I changed the viewport back to the original to avoid the cors issue. I'll look into other possible solutions for iPhone X in future updates.

Thanks for letting me know.
