### ISSUE TITLE
graphs the same

### ISSUE THREAD

**Issue by tlkhorses** [librenms/myLibreNMS#24]
It looks like all the graphs on a device are showing the same info. For instance 24hour, week etc all show the graph. Doesn't matter whether its in the Health, Graphs etc.

tk

**Comment by pheinrichs** [comment]
@tlkhorses Was this on android or iOS?

**Comment by tlkhorses** [comment]
Sorry, it is Android. Using a Galaxy S9 with Oreo.

tk

**Comment by pheinrichs** [comment]
I should be able to fix in the morning. Was just in the process of moving and I just need to push the build to android!

**Comment by pheinrichs** [comment]
@tlkhorses I've just pushed the build on android. Let me know if you have any issues with this.

**Comment by pheinrichs** [comment]
Yeah, some of that data isn't yet exposed on the API that will need to be implemented soon. Thanks for the notice.
