### ISSUE TITLE
Can't delete or modify servers

### ISSUE THREAD

**Issue by Olen** [librenms/myLibreNMS#30]
I added a server with a typo in the URL.
There is currently no way to either remove the wrong server, or modify it.

So when the app starts up, I now have multiple servers available, but only ome of then actually works...

**Comment by laf** [comment]
Well you can just delete the device from the LibreNMS webui but yes this could be added in.

**Comment by Olen** [comment]
I am not talking about a device in LibreNMS.  I am talking about a librenms-server in the app.

Start App -> "+" to "Add New Server"

**Comment by pheinrichs** [comment]
Any way to recreate this? I'm unable to do it.

I can add in a button to remove all items from the list. In the next update 

If it's bothering you until then you should be able to uninstall and reinstall the app to clear the app data.

**Comment by pheinrichs** [comment]
Side note, you should be able to swipe the items left to edit them. Does this not work?

**Comment by Olen** [comment]
Ah. I was not aware of the "Swipe left" gesture.
I now see I can edit the Token and the URL, but not the Name, for some reason.
