### ISSUE TITLE
Normal user with API token access not see any devices

### ISSUE THREAD

**Issue by florid2** [librenms/myLibreNMS#37]
myLibreNMS on iOS works fine if I login with admin account. 
I tried to create a normal user account and assigned all devices permission under that normal account. Also changed the default dashboard from private to shared-read model. Then I created an API token for that user account. 
On iOS, scan the QR code login, but in dashboard showed 0 devices and no any already assigned device in the second tab. 
Is it an expected behavior which requires admin account for mobile app login? Thanks.

**Comment by laf** [comment]
If you update LibreNMS install this should now be fixed.
