### ISSUE TITLE
myLibreNMS removed from iOS app store?

### ISSUE THREAD

**Issue by florid2** [librenms/myLibreNMS#44]
There is no search result from iOS app store for myLibrenms. 
I tried to use installed myLibrenms today but failed on start. 
ips log shows abort() called.
Any idea what happened? Thanks.

**Comment by florid2** [comment]
Weird thing, it came back on App Store again.

**Comment by epvuc** [comment]
It's gone again.

**Comment by Teddy87bln** [comment]
Yes it is. 
Not available from Germany.

**Comment by benjaminmills15** [comment]
Not available in UK

**Comment by Neustradamus** [comment]
It is a bad point.
